language: node_js
node_js:
  - '10.5.0'
cache:
  directories:
    - 'node_modules'
    - 'client/node_modules'
install:
  - 'npm i -D'
  - 'npm run heroku-postbuild'
script:
  - 'npm run test:coverage'
after_success:
  - 'npm run coverage'
